apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: 881892164822.dkr.ecr.ap-south-1.amazonaws.com/python-microservice:latest
        ports:
        - containerPort: 3000
